// LED positions queried from BoardLib kilter.db, layout_id=1 (Kilter Board Original 12x12)
// Board image coordinate system: x∈[0,144], y∈[0,156] (same as BoardMap.tsx / product_size_id=10)
//
// IMPORTANT: These coords come from the A006 query (placements+holes+leds, NO product_size filter,
// ORDER BY h.y ASC, h.x ASC). Using product_size_id=10 directly gives WRONG results because
// the same LED position number maps to a different physical hole in each product size.
// For each position, we pick the first occurrence within [0,144]×[0,156].
//
// Generated by:
//   SELECT MIN(l.position), h.x, h.y
//   FROM placements p JOIN holes h ON p.hole_id=h.id JOIN leds l ON l.hole_id=h.id
//   WHERE p.layout_id=1 GROUP BY h.x, h.y ORDER BY h.y ASC, h.x ASC
// Then: for each preset position → first (x,y) within [0,144]×[0,156]
const POSITION_COORDS: Record<number, [number, number]> = {
  0: [116, 4],   1: [112, 8],   2: [108, 4],   3: [104, 8],
  4: [100, 4],   6: [92, 4],    8: [84, 4],    10: [76, 4],
  12: [68, 4],   13: [64, 8],   14: [60, 4],   16: [52, 4],
  18: [44, 4],   20: [36, 4],   21: [28, 4],   30: [20, 4],
  32: [12, 4],   33: [4, 4],
  42: [48, 40],  43: [48, 48],  44: [52, 52],  45: [48, 56],
  46: [48, 64],  48: [20, 68],  49: [16, 64],  50: [16, 56],
  51: [20, 52],  52: [16, 48],  53: [16, 40],  54: [20, 36],
  55: [16, 32],  56: [16, 24],  57: [20, 20],  58: [16, 16],
  59: [24, 16],  60: [24, 24],  61: [48, 144], 62: [24, 32],
  63: [24, 40],  64: [56, 144], 65: [24, 48],  66: [24, 56],
  67: [60, 124], 68: [24, 64],  69: [24, 72],  70: [60, 108],
  71: [24, 80],  72: [24, 88],  73: [60, 92],  74: [56, 88],
  75: [56, 80],  76: [60, 76],  77: [56, 72],  78: [40, 32],
  79: [44, 28],  80: [40, 24],
  113: [72, 104], 116: [72, 88], 119: [72, 72],
  128: [84, 52],  129: [56, 32], 137: [68, 36],
  158: [88, 88],  183: [72, 16], 185: [84, 20], 186: [80, 24],
  221: [112, 128],
  299: [116, 84],
  367: [124, 28], 378: [120, 88], 413: [128, 24], 414: [132, 20],
  416: [136, 16], 440: [136, 152],
};

export interface LedHold {
  position: number;  // LED position sent via BLE
  role_id?: number;  // 12=Start(green), 13=Middle(cyan), 14=Finish(magenta), 15=Foot(orange)
  color?: string;    // custom hex e.g. "FF0000"
  // Board coordinates for visual overlay (null = outside 12x12 bounds, BLE-only)
  x: number | null;
  y: number | null;
}

export interface Preset {
  id: number;
  name: string;
  description: string;
  holds: LedHold[];
}

// Role IDs from placement_roles table
const START = 12;   // green   #00FF00
const MIDDLE = 13;  // cyan    #00FFFF
const FINISH = 14;  // magenta #FF00FF
const FOOT = 15;    // orange  #FFB600

function hold(
  position: number,
  roleOrColor: { role_id: number } | { color: string }
): LedHold {
  const coords = POSITION_COORDS[position] ?? null;
  return {
    position,
    ...roleOrColor,
    x: coords ? coords[0] : null,
    y: coords ? coords[1] : null,
  };
}

export const PRESETS: Preset[] = [
  {
    id: 1,
    name: 'All Corners',
    description: '4 holds at the board corners',
    holds: [
      hold(45,  { role_id: START }),   // bottom-left  (x=4,   y=52)
      hold(0,   { role_id: START }),   // bottom-right (x=140, y=4)
      hold(80,  { role_id: START }),   // top-left     (x=16,  y=88)
      hold(641, { role_id: START }),   // top-right    (no 12x12 coords — BLE only)
    ],
  },
  {
    id: 2,
    name: 'Center Cross',
    description: '5 holds in a + pattern at the center',
    holds: [
      hold(116, { role_id: MIDDLE }), // center (x=24, y=128)
      hold(74,  { role_id: MIDDLE }), // left   (x=16, y=120)
      hold(158, { role_id: MIDDLE }), // right  (x=40, y=80)
      hold(113, { role_id: MIDDLE }), // up     (x=24, y=112)
      hold(119, { role_id: MIDDLE }), // down   (x=24, y=152)
    ],
  },
  {
    id: 3,
    name: 'Bottom Row',
    description: 'All 18 holds on the bottom row',
    holds: [45, 44, 42, 33, 32, 30, 21, 20, 18, 16, 14, 12, 10, 8, 6, 4, 2, 0].map(
      (pos) => hold(pos, { role_id: FOOT })
    ),
  },
  {
    id: 4,
    name: 'Diagonal',
    description: '8 holds from bottom-left to top-right',
    holds: [45, 4, 3, 76, 137, 221, 440, 641].map(
      (pos) => hold(pos, { role_id: MIDDLE })
    ),
  },
  {
    id: 5,
    name: 'Rainbow',
    description: '4 holds across the board, one per role color',
    holds: [
      hold(12,  { role_id: START }),  // bottom-center (green)
      hold(116, { role_id: MIDDLE }), // center        (cyan)
      hold(299, { role_id: FINISH }), // top-center    (magenta)
      hold(80,  { role_id: FOOT }),   // left mid      (orange)
    ],
  },
  {
    id: 6,
    name: 'Start + Finish',
    description: '1 start hold (bottom) + 1 finish hold (top)',
    holds: [
      hold(12,  { role_id: START }),
      hold(299, { role_id: FINISH }),
    ],
  },
  {
    id: 7,
    name: 'Full Border',
    description: '103 holds around the full perimeter',
    holds: [
      0, 1, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 21, 30, 32, 33, 42, 44, 45,
      46, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
      65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
      128, 129, 185, 186, 242, 243, 299, 300, 356, 357, 413, 414, 470, 471,
      525, 526, 527,
      595, 598, 601, 604, 607, 610, 613, 616, 617, 618, 619, 620, 621, 622,
      623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636,
      637, 638, 639, 640, 641,
    ].map((pos) => hold(pos, { role_id: MIDDLE })),
  },
  {
    id: 8,
    name: 'Random 8',
    description: '8 holds spread across the board (seed 42)',
    holds: [
      hold(416, { role_id: START }),
      hold(367, { role_id: MIDDLE }),
      hold(43,  { role_id: FINISH }),
      hold(13,  { role_id: FOOT }),
      hold(79,  { role_id: START }),
      hold(3,   { role_id: MIDDLE }),
      hold(54,  { role_id: FINISH }),
      hold(618, { role_id: FOOT }),
    ],
  },
  {
    id: 9,
    name: 'Custom Red',
    description: '5 holds in pure red (custom color test)',
    holds: [67, 72, 116, 378, 629].map(
      (pos) => hold(pos, { color: 'FF0000' })
    ),
  },
  {
    id: 10,
    name: 'Strobe Test',
    description: 'Single hold — visual confirmation test',
    holds: [hold(183, { role_id: START })],
  },
];
